### ISSUE TITLE
坦克大战的逻辑是什么

### ISSUE THREAD

**Issue by wengxianxun** [MicroAnswer/wzwgame#1]
坦克大战的逻辑是什么

**Comment by Microanswer** [comment]
感谢你的关注，这里简单描述一下吧。

由3个敌方坦克和1个玩家坦克构成。

**坦克类** - 提供自己的update方法更新每一个时间点时的状态。对于敌机，将随机进行移动、子弹发射、转向。根据关卡提升，使用一个定义好的数组里面的不同的步进时间来增加难度。

**boss类** - 它是特殊的敌机类，但同时有许多和坦克类相同的功能。

**子弹类** - 虽然一颗子弹就只有一个格子，但它依然是一个独立的类，它也提供自己的update方法，以便更新自己的状态，同时通过类的形式，更提供了自己是哪个发出的子弹，这在判断子弹是否击中某个坦克时有很大的帮助。

**打Boss** - 其实把它想向成一种 [关卡提升] 时的一个额外玩法，会有助于理解。定义了一个数组，用于确定玩家击中敌机数量符合升关卡要求，符合则进行关卡提升，提升则出现打boss。

**判断击中** - 记得上面我们的子弹类吗，在屏幕里，并不是拿到所有的子弹去遍历它们有没有和某个坦克重合(击中)，而是子弹类自己判断自己是否跑到了某个坦克的位子，即实现击中。然后只需要判断击中的子弹是谁发出的以及击中的是谁，就可以确定是否完成本次击杀。

每次玩家死亡，重新复活时，所有的敌机也重新复活。因为如果不把敌机重新复活，有可能敌机占用了玩家要复活的位置。并且原生游戏机也是这样的(毕竟我就是照着那个做的[狗头])。
